//! Shell integration for panes Agentty starts: installs "reserved word" command aliases, e.g.
//! `zzzz = --dangerously-skip-permissions` for `claude`, so `claude zzzz` runs
//! `claude --dangerously-skip-permissions`.
//!
//! The user's startup files are never edited. For zsh, `ZDOTDIR` points at a generated directory
//! whose `.zshenv` restores the user's `ZDOTDIR`, sources their `.zshenv`, and registers a
//! `precmd` hook that (re)loads the alias functions after `.zshrc` has run. For bash, a generated
//! `--rcfile` sources the usual profile files first.

use crate::settings::CommandAlias;
use anyhow::Result;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

pub fn integration_dir() -> PathBuf {
    agentty_bridge::fsutil::data_dir().join("shell")
}

pub fn is_valid_word(word: &str) -> bool {
    !word.is_empty() && word.chars().all(|c| c.is_ascii_alphanumeric() || "_.:+-@".contains(c))
}

pub fn is_valid_command(command: &str) -> bool {
    !command.is_empty() && command.chars().all(|c| c.is_ascii_alphanumeric() || "_.-".contains(c))
}

/// Aliases that can be installed safely, grouped by command.
pub fn grouped(aliases: &[CommandAlias]) -> BTreeMap<String, Vec<&CommandAlias>> {
    let mut map: BTreeMap<String, Vec<&CommandAlias>> = BTreeMap::new();
    for alias in aliases.iter().filter(|a| is_valid_word(&a.keyword) && is_valid_command(&a.command)) {
        map.entry(alias.command.clone()).or_default().push(alias);
    }
    map
}

fn single_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

/// zsh functions wrapping each command; exact-match arguments are replaced by their expansion
/// (split into words with shell quoting rules).
pub fn zsh_script(aliases: &[CommandAlias]) -> String {
    let mut out = String::from("# Generated by Agentty — reserved words. Edit them in Settings.\n");
    for (command, entries) in grouped(aliases) {
        let _ = writeln!(out, "unalias {command} 2>/dev/null");
        let _ = writeln!(out, "function {command} {{");
        let _ = writeln!(out, "  local -a __agentty_args; local __agentty_word");
        let _ = writeln!(out, "  for __agentty_word in \"$@\"; do");
        let _ = writeln!(out, "    case \"$__agentty_word\" in");
        for alias in entries {
            let _ = writeln!(
                out,
                "      {}) __agentty_args+=(${{(Q)${{(z)${{:-{}}}}}}});;",
                single_quote(&alias.keyword),
                single_quote(&alias.expansion)
            );
        }
        let _ = writeln!(out, "      *) __agentty_args+=(\"$__agentty_word\");;");
        let _ = writeln!(out, "    esac");
        let _ = writeln!(out, "  done");
        let _ = writeln!(out, "  command {command} \"${{__agentty_args[@]}}\"");
        let _ = writeln!(out, "}}");
    }
    out
}

/// bash equivalent (expansions are split on whitespace).
pub fn bash_script(aliases: &[CommandAlias]) -> String {
    let mut out = String::from("# Generated by Agentty — reserved words. Edit them in Settings.\n");
    for (command, entries) in grouped(aliases) {
        let _ = writeln!(out, "unalias {command} 2>/dev/null");
        let _ = writeln!(out, "{command}() {{");
        let _ = writeln!(out, "  local __agentty_args=() __agentty_word");
        let _ = writeln!(out, "  for __agentty_word in \"$@\"; do");
        let _ = writeln!(out, "    case \"$__agentty_word\" in");
        for alias in entries {
            let _ = writeln!(
                out,
                "      {}) read -r -a __agentty_split <<< {}; __agentty_args+=(\"${{__agentty_split[@]}}\");;",
                single_quote(&alias.keyword),
                single_quote(&alias.expansion)
            );
        }
        let _ = writeln!(out, "      *) __agentty_args+=(\"$__agentty_word\");;");
        let _ = writeln!(out, "    esac");
        let _ = writeln!(out, "  done");
        let _ = writeln!(out, "  command {command} \"${{__agentty_args[@]}}\"");
        let _ = writeln!(out, "}}");
    }
    out
}

const ZSHENV: &str = r#"# Agentty shell integration (generated). Restores the user's ZDOTDIR and startup files.
if [[ -n "$AGENTTY_USER_ZDOTDIR" ]]; then
  ZDOTDIR="$AGENTTY_USER_ZDOTDIR"
else
  unset ZDOTDIR
fi
unset AGENTTY_USER_ZDOTDIR
[[ -f "${ZDOTDIR:-$HOME}/.zshenv" ]] && source "${ZDOTDIR:-$HOME}/.zshenv"
if [[ -o interactive && -n "$AGENTTY_SHELL_DIR" ]]; then
  _agentty_load_aliases() { [[ -r "$AGENTTY_SHELL_DIR/aliases.zsh" ]] && source "$AGENTTY_SHELL_DIR/aliases.zsh" }
  autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd _agentty_load_aliases
fi
"#;

const BASHRC: &str = r#"# Agentty shell integration (generated).
[ -f /etc/profile ] && . /etc/profile
if [ -f "$HOME/.bash_profile" ]; then . "$HOME/.bash_profile"
elif [ -f "$HOME/.bash_login" ]; then . "$HOME/.bash_login"
elif [ -f "$HOME/.profile" ]; then . "$HOME/.profile"
fi
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
[ -r "$AGENTTY_SHELL_DIR/aliases.bash" ] && . "$AGENTTY_SHELL_DIR/aliases.bash"
"#;

/// Writes the integration files. Called at startup and whenever aliases change.
pub fn write_files(aliases: &[CommandAlias]) -> Result<()> {
    let dir = integration_dir();
    std::fs::create_dir_all(dir.join("zsh"))?;
    write_if_changed(&dir.join("zsh").join(".zshenv"), ZSHENV)?;
    write_if_changed(&dir.join("rc.bash"), BASHRC)?;
    write_if_changed(&dir.join("aliases.zsh"), &zsh_script(aliases))?;
    write_if_changed(&dir.join("aliases.bash"), &bash_script(aliases))?;
    Ok(())
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if std::fs::read_to_string(path).ok().as_deref() != Some(content) {
        let tmp = path.with_extension("tmp");
        std::fs::write(&tmp, content)?;
        std::fs::rename(tmp, path)?;
    }
    Ok(())
}

pub enum ShellFlavor {
    Zsh,
    Bash,
    Other,
}

pub fn flavor(shell: &str) -> ShellFlavor {
    match Path::new(shell).file_name().and_then(|n| n.to_str()) {
        Some("zsh") => ShellFlavor::Zsh,
        Some("bash") => ShellFlavor::Bash,
        _ => ShellFlavor::Other,
    }
}

/// Environment for a pane's shell.
pub fn environment(shell: &str) -> Vec<(String, String)> {
    let dir = integration_dir();
    let mut env = vec![("AGENTTY_SHELL_DIR".to_string(), dir.display().to_string())];
    if let ShellFlavor::Zsh = flavor(shell) {
        if let Ok(user) = std::env::var("ZDOTDIR") {
            env.push(("AGENTTY_USER_ZDOTDIR".into(), user));
        }
        env.push(("ZDOTDIR".into(), dir.join("zsh").display().to_string()));
    }
    env
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    fn alias(keyword: &str, expansion: &str, command: &str) -> CommandAlias {
        CommandAlias { keyword: keyword.into(), expansion: expansion.into(), command: command.into() }
    }

    fn fake_command(dir: &Path) -> PathBuf {
        let bin = dir.join("bin");
        std::fs::create_dir_all(&bin).unwrap();
        let script = bin.join("agenttyprobe");
        std::fs::write(&script, "#!/bin/sh\nfor a in \"$@\"; do printf '[%s]' \"$a\"; done\n").unwrap();
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
        bin
    }

    #[test]
    fn rejects_unsafe_names() {
        let aliases = [alias("ok", "--x", "claude"), alias("bad word", "--x", "claude"), alias("k", "--x", "rm;ls")];
        let groups = grouped(&aliases);
        assert_eq!(groups.len(), 1);
        assert_eq!(groups["claude"].len(), 1);
    }

    #[test]
    fn zsh_wrapper_expands_exact_words() {
        let dir = std::env::temp_dir().join(format!("agentty-zsh-{}", std::process::id()));
        let bin = fake_command(&dir);
        let script = dir.join("aliases.zsh");
        let aliases = [alias("zzzz", "--dangerously-skip-permissions", "agenttyprobe"), alias("two", "--a 'b c'", "agenttyprobe")];
        std::fs::write(&script, zsh_script(&aliases)).unwrap();
        let output = Command::new("zsh")
            .args(["-f", "-c", &format!("source {}; agenttyprobe x zzzz two zzzzz", script.display())])
            .env("PATH", format!("{}:/usr/bin:/bin", bin.display()))
            .output()
            .unwrap();
        assert_eq!(String::from_utf8_lossy(&output.stdout), "[x][--dangerously-skip-permissions][--a][b c][zzzzz]");
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn bash_wrapper_expands_exact_words() {
        let dir = std::env::temp_dir().join(format!("agentty-bash-{}", std::process::id()));
        let bin = fake_command(&dir);
        let script = dir.join("aliases.bash");
        std::fs::write(&script, bash_script(&[alias("zzzz", "--dangerously-skip-permissions --verbose", "agenttyprobe")])).unwrap();
        let output = Command::new("bash")
            .args(["--noprofile", "--norc", "-c", &format!("source {}; agenttyprobe zzzz y", script.display())])
            .env("PATH", format!("{}:/usr/bin:/bin", bin.display()))
            .output()
            .unwrap();
        assert_eq!(String::from_utf8_lossy(&output.stdout), "[--dangerously-skip-permissions][--verbose][y]");
        std::fs::remove_dir_all(dir).ok();
    }
}
